<a href="https://colab.research.google.com/github/Rohith-Rongali/EE5179-2023/blob/main/Tutorials/Tutorial-1/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


In [26]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.26.3


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2\*3 with all elements as 5.


In [27]:
# YOUR CODE STARTS HERE

arr = np.ones((2, 3), dtype=np.int32) * 5

# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with _random_ value

**Your Task** Create a numpy array with size 2\*3 with all random values


In [28]:
# YOUR CODE STARTS HERE

rng = np.random.default_rng()
rand_arr = rng.random((2, 3))

# YOUR CODE ENDS HERE
print(rand_arr)

[[0.79381733 0.83422951 0.73275512]
 [0.20692782 0.40788956 0.64557822]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value


In [29]:
#YOUR CODE STARTS HERE

arr_sum = np.sum(rand_arr)
arr_mean = np.mean(rand_arr)
arr_max = np.max(rand_arr)
arr_min = np.min(rand_arr)

#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 3.6211975518805883
mean: 0.6035329253134314
max: 0.8342295089413844
min:0.20692781687061246


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

- Find the position of maximum and minimum value of above array
- Find the indices of maximum and minimum value along each of its columns.
- Find the indices of maximum and minimum value along each of the its rows.


In [30]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')

# YOUR CODE STARTS HERE

#Find the position of maximum and minimum value of above array

max_pos = np.argmax(arr)
max_pos_x = max_pos // arr.shape[1]
max_pos_y = max_pos % arr.shape[1]

min_pos = np.argmin(arr)
min_pos_x = min_pos //arr.shape[1]
min_pos_y = min_pos % arr.shape[1]

#Find the indices of maximum and minimum value along each of its columns.

max_pos_col = np.argmax(arr, 0)

#Find the indices of maximum and minimum value along each of the its rows.

max_pos_row = np.argmax(arr, 1)

#YOUR CODE ENDS HERE

print("Position of maximum value:", max_pos, f"= [{max_pos_x}, {max_pos_y}]")
print("Position of minimum value:", min_pos, f"= [{min_pos_x}, {min_pos_y}]")

print("Positions of maximum value along all the columns is:", max_pos_col)
print("Positions of maximum value along all the rows is:", max_pos_row)


Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Position of maximum value: 2 = [0, 2]
Position of minimum value: 6 = [1, 2]
Positions of maximum value along all the columns is: [1 1 0 1]
Positions of maximum value along all the rows is: [2 1]


Numpy Arrays vs. Python Lists?

    Why the need for numpy arrays? Can't we just use Python lists?
    Iterating over numpy arrays is slow. Slicing is faster

Python lists may contain items of different types. This flexibility comes at a price: Python lists store pointers to memory locations. On the other hand, numpy arrays are typed, where the default type is floating point. Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type. This makes access extremely fast.

If you want to know more, we will suggest that you read this from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for learning numpy, pandas and plotting. All the lessons are available as colab notebooks so that u can try out the commands on your own.
